setGeneric("arm", function(object) standardGeneric("arm"))
setGeneric("Beta", function(object) standardGeneric("Beta"))
setGeneric("breakpoints", function(object) standardGeneric("breakpoints"))
setGeneric("calculateTransitionProbability", function(object, options, ...) standardGeneric("calculateTransitionProbability"))
setGeneric("calculateEmissionProbability", function(object, options, ...) standardGeneric("calculateEmissionProbability"))
setGeneric("cnEmission", function(x, options, ...) standardGeneric("cnEmission"))
setGeneric("cn.location", function(object) standardGeneric("cn.location"))
setGeneric("gtEmission", function(x, options, ...) standardGeneric("gtEmission"))
setGeneric(".gtEmission.ICE", function(x, options, ...) standardGeneric(".gtEmission.ICE"))
setGeneric("cn.ICE", function(object) standardGeneric("cn.ICE"))
setGeneric("cn.ICE<-", function(object, value) standardGeneric("cn.ICE<-"))
setGeneric("gt.ICE", function(object) standardGeneric("gt.ICE"))
setGeneric("gt.ICE<-", function(object, value) standardGeneric("gt.ICE<-"))
setGeneric("hmmOptions", function(object) standardGeneric("hmmOptions"))
setGeneric("pi", function(object) standardGeneric("pi"))
setGeneric("predictions", function(object) standardGeneric("predictions"))
setGeneric("predictions<-", function(object, value) standardGeneric("predictions<-"))
setGeneric("SnpClass", function(object) standardGeneric("SnpClass"))
setGeneric("states", function(object) standardGeneric("states"))
setGeneric("tau", function(object) standardGeneric("tau"))
setGeneric("tau.scale", function(object) standardGeneric("tau.scale"))
