##setGeneric("arm", function(object) standardGeneric("arm"))
##setGeneric("Beta", function(object) standardGeneric("Beta"))
setGeneric("breakpoints", function(object) standardGeneric("breakpoints"))
setGeneric("breakpoints<-", function(object, value) standardGeneric("breakpoints<-"))
setGeneric("calculateBreakpoints", function(object, ...) standardGeneric("calculateBreakpoints"))
setGeneric("calculateDistance", function(object) standardGeneric("calculateDistance"))
##setGeneric("calculateTransitionProbability", function(object, options, ...) standardGeneric("calculateTransitionProbability"))
##setGeneric("calculateEmissionProbability", function(object, options, ...) standardGeneric("calculateEmissionProbability"))
##setGeneric("cnEmission", function(x, options, ...) standardGeneric("cnEmission"))
setGeneric("calls.emission", function(object) standardGeneric("calls.emission"))
setGeneric("copyNumber.emission", function(object) standardGeneric("copyNumber.emission"))
setGeneric("copyNumber.location", function(object) standardGeneric("copyNumber.location"))
##setGeneric("cn.robustSE", function(object) standardGeneric("cn.robustSE"))
##setGeneric("gtEmission", function(x, options, ...) standardGeneric("gtEmission"))
##setGeneric(".gtEmission.ICE", function(x, options, ...) standardGeneric(".gtEmission.ICE"))
setGeneric("copyNumber.ICE", function(object) standardGeneric("copyNumber.ICE"))
setGeneric("copyNumber.ICE<-", function(object, value) standardGeneric("copyNumber.ICE<-"))
setGeneric("calls.ICE", function(object) standardGeneric("calls.ICE"))
setGeneric("calls.ICE<-", function(object, value) standardGeneric("calls.ICE<-"))
setGeneric("hmm", function(object, params) standardGeneric("hmm"))
##setGeneric("hmmOptions", function(object) standardGeneric("hmmOptions"))
##setGeneric("hmmOptions<-", function(object, value) standardGeneric("hmmOptions<-"))
setGeneric("pi", function(object) standardGeneric("pi"))
setGeneric("predictions", function(object) standardGeneric("predictions"))
setGeneric("predictions<-", function(object, value) standardGeneric("predictions<-"))
##setGeneric("SnpClass", function(object) standardGeneric("SnpClass"))
setGeneric("states", function(object) standardGeneric("states"))
setGeneric("states<-", function(object, value) standardGeneric("states<-"))
setGeneric("tau", function(object) standardGeneric("tau"))
##setGeneric("tau.scale", function(object) standardGeneric("tau.scale"))

setGeneric("emission<-", function(object, value) standardGeneric("emission<-"))
setGeneric("emission", function(object) standardGeneric("emission"))
setGeneric("ratio", function(object) standardGeneric("ratio"))
setGeneric("ratio<-", function(object, value) standardGeneric("ratio<-"))
setGeneric("genomicDistance", function(object) standardGeneric("genomicDistance"))
setGeneric("genomicDistance<-", function(object, value) standardGeneric("genomicDistance<-"))
setGeneric("snpdata", function(object) standardGeneric("snpdata"))
setGeneric("transitionScale", function(object) standardGeneric("transitionScale"))
setGeneric("transitionScale<-", function(object, value) standardGeneric("transitionScale<-"))

