setGeneric("breakpoints", function(object) standardGeneric("breakpoints"))
setGeneric("breakpoints<-", function(object, value) standardGeneric("breakpoints<-"))
setGeneric("calculateBreakpoints", function(object, ...) standardGeneric("calculateBreakpoints"))
setGeneric("calculateDistance", function(object) standardGeneric("calculateDistance"))
setGeneric("physicalDistance", function(object) standardGeneric("physicalDistance"))
##setGeneric("calls.emission", function(object) standardGeneric("calls.emission"))
##setGeneric("copyNumber.emission", function(object) standardGeneric("copyNumber.emission"))
setGeneric("copyNumber.location", function(object) standardGeneric("copyNumber.location"))
setGeneric("copyNumber.location<-", function(object, value) standardGeneric("copyNumber.location<-"))
setGeneric("copyNumber.ICE", function(object) standardGeneric("copyNumber.ICE"))
setGeneric("copyNumber.ICE<-", function(object, value) standardGeneric("copyNumber.ICE<-"))
setGeneric("calls.ICE", function(object) standardGeneric("calls.ICE"))
setGeneric("calls.ICE<-", function(object, value) standardGeneric("calls.ICE<-"))
setGeneric("hmm", function(object, params) standardGeneric("hmm"))
setGeneric("Pi", function(object) standardGeneric("Pi"))
setGeneric("predictions", function(object) standardGeneric("predictions"))
setGeneric("predictions<-", function(object, value) standardGeneric("predictions<-"))

setGeneric("states", function(object) standardGeneric("states"))
setGeneric("states<-", function(object, value) standardGeneric("states<-"))
setGeneric("tau", function(object) standardGeneric("tau"))

setGeneric("emission<-", function(object, value) standardGeneric("emission<-"))
setGeneric("emission", function(object) standardGeneric("emission"))
setGeneric("genomicDistance", function(object) standardGeneric("genomicDistance"))
setGeneric("genomicDistance<-", function(object, value) standardGeneric("genomicDistance<-"))

setGeneric("transitionScale", function(object) standardGeneric("transitionScale"))
setGeneric("transitionScale<-", function(object, value) standardGeneric("transitionScale<-"))

setGeneric("initialStateProbability", function(object) standardGeneric("initialStateProbability"))
setGeneric("probHomCall", function(object) standardGeneric("probHomCall"))
setGeneric("probHomCall<-", function(object, value) standardGeneric("probHomCall<-"))
setGeneric("snpset", function(object) standardGeneric("snpset"))
setGeneric("snpset<-", function(object, value) standardGeneric("snpset<-"))
setGeneric("term5", function(object) standardGeneric("term5"))
setGeneric("term5<-", function(object, value) standardGeneric("term5<-"))

